
server:
  port: 8080

spring:
  datasource:
    name: pile
    username: root
    password: root
    url: jdbc:mysql://123.207.233.171:3306/charg
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.zy.charg.bean

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
