
server:
  port: 8080

spring:
  datasource:
    name: pile
    username: root
    password: root
    url: jdbc:mysql://123.207.233.171:3306/charg?userSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.zy.charg.bean

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
